version: '2'

networks:
  tnet:
    driver: bridge

services:
  mysql:
    restart: always
    image: mysql:5.6
    ports:
     - "3306:3306"
    networks:
     - tnet
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
  phpapp:
    privileged: true
    image: "seregatte/php:5.6-apache"
    build: "build"
    ports:
     - "9000:9000"
     - "8000:80"
    networks:
     - tnet
    environment:
     - XDEBUG_ENABLED=1
     - APACHE_DOCUMENT_ROOT=/var/www/public
     - XDEBUG_CONFIG=idekey=VSCODE remote_host=192.168.64.1
    volumes:
     - "./resources/public:/var/www/public"
    depends_on:
     - mysql